# Generated by Django 2.2 on 2019-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20190505_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
