# Generated by Django 2.2 on 2019-05-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20190506_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='portions',
            new_name='servings',
        ),
    ]
