# Generated by Django 2.2 on 2019-05-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20190507_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Kategorie-Titel'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Lebensmittel'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Food', verbose_name='Lebensmittel'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Anmerkungen'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, to='recipes.Category', verbose_name='Kategorien'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(verbose_name='Zubereitung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=100, verbose_name='Zubereitungszeit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Portionen'),
        ),
    ]
