# Generated by Django 2.2 on 2019-05-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20190507_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Food', verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, to='recipes.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(verbose_name='Directions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=100, verbose_name='Prep time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
