# Generated by Django 2.2 on 2019-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20190507_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='introduction',
            field=models.TextField(null=True, verbose_name='Introduction'),
        ),
    ]
