# Generated by Django 3.0.5 on 2020-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20200409_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Titelbild'),
        ),
    ]
