# Generated by Django 3.0.5 on 2020-04-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_image_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(null=True, related_name='_recipe_related_recipes_+', to='recipes.Recipe', verbose_name='zugehörige Rezepte'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Lebensmittel'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
    ]
