# Generated by Django 3.0.5 on 2020-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_auto_20200417_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe', verbose_name='zugehörige Rezepte'),
        ),
    ]
