# Generated by Django 3.0.5 on 2020-05-07 11:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_recipe_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='public',
            field=models.BooleanField(default=False, verbose_name='für alle sichtbar'),
        ),
    ]
