# Generated by Django 3.0.5 on 2020-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_auto_20200507_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Anzahl'),
        ),
    ]
