# Generated by Django 3.1.6 on 2021-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_auto_20200511_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='secret_notes',
            field=models.TextField(blank=True, verbose_name='Geheime Notizen'),
        ),
    ]
