# Generated by Django 3.1.6 on 2021-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_auto_20210207_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True, verbose_name='Zubereitung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='introduction',
            field=models.TextField(blank=True, default='', verbose_name='Einleitung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zubereitungszeit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True, verbose_name='Portionen'),
        ),
    ]
