# Generated by Django 3.2.12 on 2022-11-07 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0040_shoppinglist_shoppinglistrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistrecipe',
            old_name='conversion_factor',
            new_name='servings',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
